AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      EnableDnsSupport: true
      EnableDnsHostnames: true
      CidrBlock: 10.0.1.0/24 # 10.0.1.1 - 10.0.1.254

  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:  !Ref VPC
      CidrBlock: 10.0.1.0/25 # 10.0.1.0 - 10.0.1.127
      AvailabilityZone: us-east-1b

  Server1:
    Type: AWS::EC2::Instance
    Metadata:
      Comment: Install Salt
      AWS::CloudFormation::Init:
        config:
          packages:
            apt:
              openjdk-8-jre: []
    CreationPolicy:
      ResourceSignal:
        Timeout: PT5M
    Properties:
      SubnetId: !Ref Subnet
      AvailabilityZone: us-east-1b
      ImageId: ami-0a313d6098716f372
      InstanceType: t2.micro
      KeyName: white_box
      SecurityGroupIds:
        - !Ref SSHSecurityGroup
        - !Ref ServerSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update
          # Install package manager for Python packages
          apt-get install python-pip -y
          # Install AWS CF helper scripts
          pip install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
          # Install salt master
          curl -o bootstrap-salt.sh -L https://bootstrap.saltstack.com
          sudo sh bootstrap-salt.sh git v2018.3.3
          # sudo sh bootstrap-salt.sh -M -N git v2018.3.3
          # Start cfn-init
          cfn-init --region ${AWS::Region} --stack ${AWS::StackId} --resource Server1
          # All done so signal success
          cfn-signal --region ${AWS::Region} --stack ${AWS::StackId} --resource Server1 --exit-code $?

  EIP1:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref Server1

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22

  ServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow to access web application
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
