AWSTemplateFormatVersion: 2010-09-09
Metadata:
  License: GNU GPLv3
Description: "AWS CloudFormation sample template to demo how to:
                * create two EC2 instances in non-default VPC
                * use CF init (AWS::CloudFormation::Init) and UserData for instance initialization
                * install salt master and minion
              Following main resources are created:
                * VPC
                * one subnet
                * internet gateway
                * two EC2 instances"

Parameters:
  KeyName:
    Description: EC2 ssh key
    Type: AWS::EC2::KeyPair::KeyName
  UbuntuAMI:
    Description: Ubuntu 18 AMI ID
    Type: String
    Default: ami-0a313d6098716f372

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      EnableDnsSupport: true
      EnableDnsHostnames: true
      CidrBlock: 10.0.1.0/24 # 10.0.1.1 - 10.0.1.254
      Tags:
        - Key: Stack
          Value: !Sub ${AWS::StackName}
        - Key: Name
          Value: !Sub ${AWS::StackName}__VPC

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:  !Ref VPC
      CidrBlock: 10.0.1.0/25 # 10.0.1.1 - 10.0.1.127
      AvailabilityZone: us-east-1b
      Tags:
        - Key: Stack
          Value: !Sub ${AWS::StackName}
        - Key: Name
          Value: !Sub ${AWS::StackName}__PublicSubnet

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:  !Ref VPC
      CidrBlock: 10.0.1.128/25 # 10.0.1.128 - 10.0.1.255
      AvailabilityZone: us-east-1b
      Tags:
        - Key: Stack
          Value: !Sub ${AWS::StackName}
        - Key: Name
          Value: !Sub ${AWS::StackName}__PrivateSubnet

  Server1:
    Type: AWS::EC2::Instance
    DependsOn:
      - RouteTableForPublicSubnetRoute1
      - RouteTableForPrivateSubnetRoute1
    Metadata:
      AWS::CloudFormation::Init:
        config:
          packages:
            apt:
              openjdk-11-jre: []
    CreationPolicy:
      ResourceSignal:
        Timeout: PT5M
    Properties:
      AvailabilityZone: us-east-1b
      ImageId: !Ref UbuntuAMI
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update
          echo "Install package manager for Python packages"
          apt-get install python-pip -y
          echo "Install AWS CF helper scripts"
          pip install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
          echo "Download salt bootstrap script"
          curl -o bootstrap-salt.sh -L https://bootstrap.saltstack.com
          echo "Install salt master and minion"
          sh bootstrap-salt.sh -M -P git v2018.3.3
          echo "Update /etc/salt/master cfg"
          cat >> /etc/salt/master <<EOF
          # The address of the interface to bind to:
          interface: 10.0.1.4
          EOF
          echo "Update /etc/salt/minion cfg"
          cat >> /etc/salt/minion <<EOF
          # Set the location of the salt master server.
          master: 10.0.1.4
          EOF
          echo "Restart salt master"
          systemctl restart salt-master.service
          echo "Restart salt minion"
          systemctl restart salt-minion.service
          echo "Wait until all public key of salt minions are accepted ..."
          while [ $(ls -A /etc/salt/pki/master/minions | wc -l) != 2 ]; do
            sleep 15
            salt-key --accept-all -y
          done
          echo "Start cfn-init"
          cfn-init --region ${AWS::Region} --stack ${AWS::StackId} --resource Server1
          echo "All done send success signal"
          cfn-signal --region ${AWS::Region} --stack ${AWS::StackId} --resource Server1 --exit-code $?
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeleteOnTermination: true
          SubnetId: !Ref PublicSubnet
          PrivateIpAddress: 10.0.1.4
          Description: Primary network interface
          DeviceIndex: 0
          GroupSet:
            - !Ref SSHSecurityGroup
            - !Ref ServerSecurityGroup
      Tags:
        - Key: Stack
          Value: !Sub ${AWS::StackName}
        - Key: Name
          Value: !Sub ${AWS::StackName}__Server1_master

  Server2:
    Type: AWS::EC2::Instance
    DependsOn:
      - RouteTableForPublicSubnetRoute1
      - RouteTableForPrivateSubnetRoute1
    Metadata:
      AWS::CloudFormation::Init:
        config:
          packages:
            apt:
              openjdk-11-jre: []
    CreationPolicy:
      ResourceSignal:
        Timeout: PT5M
    Properties:
      AvailabilityZone: us-east-1b
      ImageId: !Ref UbuntuAMI
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update
          echo "Install package manager for Python packages"
          apt-get install python-pip -y
          echo "Install AWS CF helper scripts"
          pip install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
          echo "Download salt bootstrap script"
          curl -o bootstrap-salt.sh -L https://bootstrap.saltstack.com
          echo "Install salt minion"
          sh bootstrap-salt.sh -P git v2018.3.3
          echo "Update /etc/salt/minion cfg"
          cat >> /etc/salt/minion <<EOF
          # Set the location of the salt master server.
          master: 10.0.1.4
          EOF
          echo "Restart salt minion"
          systemctl restart salt-minion.service
          echo "Start cfn-init"
          cfn-init --region ${AWS::Region} --stack ${AWS::StackId} --resource Server2
          echo "All done so signal success"
          cfn-signal --region ${AWS::Region} --stack ${AWS::StackId} --resource Server2 --exit-code $?
      NetworkInterfaces:
        - AssociatePublicIpAddress: false
          DeleteOnTermination: true
          SubnetId: !Ref PrivateSubnet
          PrivateIpAddress: 10.0.1.132
          Description: Primary network interface
          DeviceIndex: 0
          GroupSet:
            - !Ref SSHSecurityGroup
            - !Ref ServerSecurityGroup
      Tags:
        - Key: Stack
          Value: !Sub ${AWS::StackName}
        - Key: Name
          Value: !Sub ${AWS::StackName}__Server2_minion

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Stack
          Value: !Sub ${AWS::StackName}
        - Key: Name
          Value: !Sub ${AWS::StackName}__InternetGateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  NATGateway:
    Type: AWS::EC2::NatGateway
    DependsOn: ElasticIP
    Properties:
      AllocationId:
        Fn::GetAtt:
          - ElasticIP
          - AllocationId
      SubnetId: !Ref PublicSubnet

  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  RouteTableForPublicSubnet:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Stack
          Value: !Sub ${AWS::StackName}
        - Key: Name
          Value: !Sub ${AWS::StackName}__RouteTableForPublicSubnet

  RouteTableForPublicSubnetAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref RouteTableForPublicSubnet

  RouteTableForPublicSubnetRoute1:
    Type: AWS::EC2::Route
    DependsOn: InternetGateway
    Properties:
      RouteTableId: !Ref RouteTableForPublicSubnet
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  RouteTableForPrivateSubnet:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Stack
          Value: !Sub ${AWS::StackName}
        - Key: Name
          Value: !Sub ${AWS::StackName}__RouteTableForPrivateSubnet

  RouteTableForPrivateSubnetAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet
      RouteTableId: !Ref RouteTableForPrivateSubnet

  RouteTableForPrivateSubnetRoute1:
    Type: AWS::EC2::Route
    DependsOn: NATGateway
    Properties:
      RouteTableId: !Ref RouteTableForPrivateSubnet
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGateway

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
      Tags:
        - Key: Stack
          Value: !Sub ${AWS::StackName}
        - Key: Name
          Value: !Sub ${AWS::StackName}__SSHSecurityGroup

  ServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow to access web application
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 10.0.1.0/24
      Tags:
        - Key: Stack
          Value: !Sub ${AWS::StackName}
        - Key: Name
          Value: !Sub ${AWS::StackName}__ServerSecurityGroup
